import 'package:recips_app/models/recipe_model.dart';

List<Recipe> recipeDetails() {
  List<Recipe> recipeList = [
    Recipe(
      id: 1,
      name: "Classic Spaghetti Bolognese",
      ingredients: [
        "1 lb spaghetti",
        "1 lb ground beef",
        "1 onion, chopped",
        "2 cloves garlic, minced",
        "1 (28 oz) can crushed tomatoes",
        "1 tsp dried oregano",
        "1/2 tsp salt",
        "1/4 tsp black pepper",
        "2 tbsp olive oil",
      ],
      instructions: [
        "Cook spaghetti according to package directions.",
        "In a large skillet, brown ground beef over medium heat. Drain off any excess grease.",
        "Add onion and garlic to the skillet and cook until softened.",
        "Stir in crushed tomatoes, oregano, salt, and pepper. Bring to a simmer and cook for 15 minutes.",
        "Serve the sauce over spaghetti.",
      ],
      prepTimeMinutes: 15,
      cookTimeMinutes: 30,
      servings: 6,
      difficulty: "Easy",
      cuisine: "Italian",
      caloriesPerServing: 450,
      tags: ["pasta", "beef", "tomato sauce"],
      userId: 101,
      image: "https://cdn.dummyjson.com/recipe-images/1.webp",
      rating: 4.5,
      reviewCount: 120,
      mealType: ["dinner"],
    ),
    Recipe(
      id: 2,
      name: "Chicken Stir-Fry",
      ingredients: [
        "1 lb boneless, skinless chicken breasts, cut into bite-sized pieces",
        "1 bell pepper, sliced",
        "1 onion, sliced",
        "1 cup broccoli florets",
        "1/2 cup soy sauce",
        "1/4 cup honey",
        "2 tbsp cornstarch",
        "1 tbsp sesame oil",
      ],
      instructions: [
        "In a bowl, whisk together soy sauce, honey, and cornstarch.",
        "Heat sesame oil in a large skillet or wok over medium-high heat.",
        "Add chicken and cook until browned.",
        "Add bell pepper, onion, and broccoli to the skillet and cook until tender-crisp.",
        "Pour the sauce over the chicken and vegetables and cook until thickened.",
        "Serve over rice.",
      ],
      prepTimeMinutes: 20,
      cookTimeMinutes: 25,
      servings: 4,
      difficulty: "Medium",
      cuisine: "Asian",
      caloriesPerServing: 380,
      tags: ["chicken", "vegetables", "stir-fry"],
      userId: 102,
      image: "https://cdn.dummyjson.com/recipe-images/1.webp",
      rating: 4.2,
      reviewCount: 95,
      mealType: ["lunch", "dinner"],
    ),
    Recipe(
      id: 3,
      name: "Chocolate Chip Cookies",
      ingredients: [
        "2 1/4 cups all-purpose flour",
        "1 tsp baking soda",
        "1 tsp salt",
        "1 cup (2 sticks) unsalted butter, softened",
        "3/4 cup granulated sugar",
        "3/4 cup packed brown sugar",
        "1 tsp vanilla extract",
        "2 large eggs",
        "2 cups chocolate chips",
      ],
      instructions: [
        "Preheat oven to 375 degrees F (190 degrees C).",
        "In a small bowl, whisk together flour, baking soda, and salt.",
        "In a large bowl, cream together butter, granulated sugar, and brown sugar until smooth.",
        "Beat in vanilla extract and eggs until well combined.",
        "Gradually add the dry ingredients to the wet ingredients, mixing until just combined.",
        "Stir in chocolate chips.",
        "Drop by rounded tablespoons onto ungreased baking sheets.",
        "Bake for 9-11 minutes, or until golden brown.",
        "Let cool on baking sheets for a few minutes before transferring to a wire rack to cool completely.",
      ],
      prepTimeMinutes: 10,
      cookTimeMinutes: 10,
      servings: 24,
      difficulty: "Easy",
      cuisine: "American",
      caloriesPerServing: 150,
      tags: ["dessert", "cookies", "chocolate"],
      userId: 103,
      image: "https://cdn.dummyjson.com/recipe-images/1.webp",
      rating: 4.8,
      reviewCount: 150,
      mealType: ["dessert", "snack"],
    ),
  ];

  return recipeList;
}
